# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookrequest',
            fields=[
                ('idbookrequest', models.IntegerField(db_column='idBookRequest', primary_key=True, serialize=False)),
                ('starttime', models.DateTimeField(blank=True, db_column='StartTime', null=True)),
                ('endtime', models.DateTimeField(blank=True, db_column='EndTime', null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'bookrequest',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('etypeid', models.IntegerField(db_column='EtypeID', primary_key=True, serialize=False)),
                ('ename', models.CharField(blank=True, db_column='EName', max_length=45, null=True)),
            ],
            options={
                'db_table': 'equipment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venueid', models.IntegerField(db_column='VenueID', primary_key=True, serialize=False)),
                ('venuename', models.CharField(blank=True, db_column='VenueName', max_length=45, null=True)),
                ('capacity', models.IntegerField(blank=True, db_column='Capacity', null=True)),
                ('dno', models.ForeignKey(blank=True, db_column='DNo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='log.Department')),
            ],
            options={
                'db_table': 'venue',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='venueid',
            field=models.ForeignKey(blank=True, db_column='VenueID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rooms.Venue'),
        ),
    ]
