# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookrequest',
            fields=[
                ('idbookrequest', models.IntegerField(db_column='idBookRequest', primary_key=True, serialize=False)),
                ('starttime', models.DateTimeField(blank=True, db_column='StartTime', null=True)),
                ('endtime', models.DateTimeField(blank=True, db_column='EndTime', null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending Approval', 'Pending Approval'), ('Denied Approval', 'Denied Approval'), ('APPROVED', 'APPROVED'), ('Prempted by Staff', 'Prempted by Staff'), ('Cancelled', 'Cancelled')], default='Pending Approval', max_length=45, null=True)),
            ],
            options={
                'db_table': 'bookrequest',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('etypeid', models.IntegerField(db_column='EtypeID', primary_key=True, serialize=False)),
                ('ename', models.CharField(blank=True, db_column='EName', max_length=45, null=True)),
            ],
            options={
                'db_table': 'equipment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FacultyBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.ForeignKey(db_column='idBookRequest', on_delete=django.db.models.deletion.CASCADE, to='rooms.Bookrequest')),
                ('facultyid', models.ForeignKey(db_column='FacultyID', on_delete=django.db.models.deletion.DO_NOTHING, to='log.Faculty')),
            ],
            options={
                'db_table': 'faculty_book',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.ForeignKey(db_column='idBookRequest', on_delete=django.db.models.deletion.CASCADE, to='rooms.Bookrequest')),
                ('usn', models.ForeignKey(db_column='USN', on_delete=django.db.models.deletion.DO_NOTHING, to='log.Student')),
            ],
            options={
                'db_table': 'student_book',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venueid', models.IntegerField(db_column='VenueID', primary_key=True, serialize=False)),
                ('venuename', models.CharField(blank=True, db_column='VenueName', max_length=45, null=True)),
                ('capacity', models.IntegerField(blank=True, db_column='Capacity', null=True)),
                ('dno', models.ForeignKey(blank=True, db_column='DNo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='log.Department')),
            ],
            options={
                'db_table': 'venue',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VenueEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
                ('etypeid', models.ForeignKey(db_column='EtypeID', on_delete=django.db.models.deletion.CASCADE, to='rooms.Equipment')),
                ('venueid', models.ForeignKey(db_column='VenueID', on_delete=django.db.models.deletion.CASCADE, to='rooms.Venue')),
            ],
            options={
                'db_table': 'venue_equipment',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='venueid',
            field=models.ForeignKey(blank=True, db_column='VenueID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rooms.Venue'),
        ),
        migrations.AlterUniqueTogether(
            name='venueequipment',
            unique_together=set([('venueid', 'etypeid')]),
        ),
        migrations.AlterUniqueTogether(
            name='studentbook',
            unique_together=set([('usn', 'bookid')]),
        ),
        migrations.AlterUniqueTogether(
            name='facultybook',
            unique_together=set([('facultyid', 'bookid')]),
        ),
    ]
