# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('idfault', models.IntegerField(db_column=b'idFault', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[(b'Pending', b'Pending Repair'), (b'Repairing', b'Getting Repaired'), (b'Completed', b'Completed Repair')], db_column=b'Status', default=b'Pending', max_length=45, null=True)),
                ('etype', models.ForeignKey(blank=True, db_column=b'etype', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rooms.Equipment')),
                ('venueid', models.ForeignKey(blank=True, db_column=b'VenueID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rooms.Venue')),
            ],
            options={
                'db_table': 'fault',
                'managed': True,
            },
        ),
    ]
