# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0002_auto_20161107_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('idfault', models.IntegerField(db_column=b'idFault', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, db_column=b'Status', max_length=45, null=True)),
                ('etype', models.ForeignKey(blank=True, db_column=b'etype', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rooms.Equipment')),
                ('venueid', models.ForeignKey(blank=True, db_column=b'VenueID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rooms.Venue')),
            ],
            options={
                'db_table': 'fault',
                'managed': True,
            },
        ),
    ]
