# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyid', models.ForeignKey(db_column=b'FacultyID', on_delete=django.db.models.deletion.CASCADE, to='log.Faculty')),
            ],
            options={
                'db_table': 'faculty_request',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Resourcereq',
            fields=[
                ('reqid', models.IntegerField(db_column=b'ReqID', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[(b'Pending Approval', b'Pending Approval'), (b'Denied Approval', b'Denied Approval'), (b'APPROVED', b'APPROVED')], db_column=b'Status', max_length=45, null=True)),
                ('etypeid', models.ForeignKey(blank=True, db_column=b'EtypeID', null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.Equipment')),
                ('venueid', models.ForeignKey(blank=True, db_column=b'VenueID', null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.Venue')),
            ],
            options={
                'db_table': 'resourcereq',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reqid', models.ForeignKey(db_column=b'ReqID', on_delete=django.db.models.deletion.CASCADE, to='req.Resourcereq')),
                ('usn', models.ForeignKey(db_column=b'USN', on_delete=django.db.models.deletion.CASCADE, to='log.Student')),
            ],
            options={
                'db_table': 'student_request',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='facultyrequest',
            name='reqid',
            field=models.ForeignKey(db_column=b'ReqID', on_delete=django.db.models.deletion.CASCADE, to='req.Resourcereq'),
        ),
        migrations.AlterUniqueTogether(
            name='studentrequest',
            unique_together=set([('usn', 'reqid')]),
        ),
        migrations.AlterUniqueTogether(
            name='facultyrequest',
            unique_together=set([('facultyid', 'reqid')]),
        ),
    ]
