# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_userprofile'),
        ('req', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyid', models.ForeignKey(db_column=b'FacultyID', on_delete=django.db.models.deletion.DO_NOTHING, to='log.Faculty')),
                ('reqid', models.ForeignKey(db_column=b'ReqID', on_delete=django.db.models.deletion.DO_NOTHING, to='req.Resourcereq')),
            ],
            options={
                'db_table': 'faculty_request',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reqid', models.ForeignKey(db_column=b'ReqID', on_delete=django.db.models.deletion.DO_NOTHING, to='req.Resourcereq')),
                ('usn', models.ForeignKey(db_column=b'USN', on_delete=django.db.models.deletion.DO_NOTHING, to='log.Student')),
            ],
            options={
                'db_table': 'student_request',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='studentrequest',
            unique_together=set([('usn', 'reqid')]),
        ),
        migrations.AlterUniqueTogether(
            name='facultyrequest',
            unique_together=set([('facultyid', 'reqid')]),
        ),
    ]
