# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 16:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dno', models.IntegerField(db_column=b'DNo', primary_key=True, serialize=False)),
                ('dname', models.CharField(blank=True, db_column=b'DName', max_length=45)),
            ],
            options={
                'db_table': 'department',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('facultyid', models.CharField(db_column=b'FacultyID', max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column=b'Name', max_length=45)),
                ('dno', models.ForeignKey(blank=True, db_column=b'DNo', null=True, on_delete=django.db.models.deletion.CASCADE, to='log.Department')),
            ],
            options={
                'db_table': 'faculty',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('usn', models.CharField(db_column=b'USN', max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column=b'Name', max_length=45)),
                ('dno', models.ForeignKey(blank=True, db_column=b'DNo', null=True, on_delete=django.db.models.deletion.CASCADE, to='log.Department')),
            ],
            options={
                'db_table': 'student',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(choices=[(b'SA', b'SysAdmin'), (b'S', b'Student'), (b'F', b'Faculty'), (b'P', b'Personnel')], default=b'SA', max_length=10)),
                ('priorityLevel', models.IntegerField(default=0)),
                ('faculty', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='log.Faculty')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='log.Student')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
