# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dno', models.IntegerField(db_column=b'DNo', primary_key=True, serialize=False)),
                ('dname', models.CharField(blank=True, db_column=b'DName', max_length=45)),
            ],
            options={
                'db_table': 'department',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('facultyid', models.CharField(db_column=b'FacultyID', max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column=b'Name', max_length=45)),
                ('dno', models.ForeignKey(blank=True, db_column=b'DNo', null=True, on_delete=django.db.models.deletion.CASCADE, to='log.Department')),
            ],
            options={
                'db_table': 'faculty',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('usn', models.CharField(db_column=b'USN', max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column=b'Name', max_length=45)),
                ('dno', models.ForeignKey(blank=True, db_column=b'DNo', null=True, on_delete=django.db.models.deletion.CASCADE, to='log.Department')),
            ],
            options={
                'db_table': 'student',
                'managed': True,
            },
        ),
    ]
