# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 06:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(choices=[(b'SA', b'SysAdmin'), (b'S', b'Student'), (b'F', b'Faculty'), (b'P', b'Personnel')], default=b'SA', max_length=10)),
                ('priorityLevel', models.IntegerField(default=0)),
                ('faculty', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='log.Faculty')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='log.Student')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
